- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install devel packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - curl
    - libtool
    - automake
    - libbz2-dev
    - libsqlite3-dev
    - libncurses-dev
    - libreadline-dev
    - libffi-dev
    - tk-dev
    - liblzma-dev
    - libssl-dev
    - python-openssl
    - libz-dev
    - python3-pip

- name: Update hosts
  become: true
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ hostvars[item]['internal_ip'] }}\t{{ hostvars[item]['internal_hostname']}}"
    state: present
    backup: yes
  when: inventory_hostname != "{{ item }}" or inventory_hostname == "{{ item }}"
  with_items: "{{groups['all']}}"
